edmcouncil/onto-viewer

config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/loader/saxparser/WeaselConfigurationHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlAnnotationPropertyValue.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/taxonomy/OwlTaxonomyImpl.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/AnnotationsDataHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataExtractor.java
Eliminating xsd attributes from literals.
=> Fibo 57 eliminate xsd attributions from literals

weasel_config.xml
New organization of the group elements. Group elements got new names.
=> new groups and renames

config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/loader/saxparser/WeaselConfigurationHandler.java, config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/WeaselConfigKeys.java, config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/impl/WeaselConfiguration.java, config/src/main/java/org/edmcouncil/spec/fibo/config/utils/files/FileSystemManager.java, weasel/pom.xml, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/WeaselOwlType.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/WeaselOntologyManager.java, weasel_config.xml
Loading of ontology using URL and path.
=>  Read fibo from url

view/pom.xml, view/src/main/java/org/edmcouncil/spec/fibo/view/controller/ModuleController.java, view/src/main/java/org/edmcouncil/spec/fibo/view/controller/SearchController.java, view/src/main/java/org/edmcouncil/spec/fibo/view/service/SearchService.java, view/src/main/java/org/edmcouncil/spec/fibo/view/swagger/SwaggerConfig.java, view/src/main/java/org/edmcouncil/spec/fibo/view/util/ModelBuilder.java, view/src/main/webapp/WEB-INF/jsp/page/elements/view.jsp, view/src/main/webapp/WEB-INF/jsp/page/elements/viewGrouped.jsp, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlDetails.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlGroupedDetails.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlListDetailsDetails.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/WeaselOntologyManager.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/utils/StringSplitter.java
Swagger configured for fibo-viewer.
Swagger UI is running on _root-app_/**swagger-ui.html**
=> Configure swagger for project

config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/GroupType.java, config/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/impl/WeaselConfiguration.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/WeaselOntologyManager.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java
When searching
https://spec.edmcouncil.org/fibo/ontology/FND/Quantities/QuantitiesAndUnits/Quantity
field IS-A restrictions inherited from superclasses: has no items but is displaying.
=> Field display bug without elements

view/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/PropertyRenderTag.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/OwlSimpleProperty.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlAnnotationIri.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/AnnotationsDataHandler.java, weasel_config.xml
> Change displaying IRIs to the same used in taxonomy. Now IRIs displaying as link.
IRIs has been prepared for displaying labels. Temporarily, the last part of the link is displayed instead.
=> Change displaying IRIs to the same used in taxonomy

view/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/TreeRenderTag.java, view/src/main/webapp/WEB-INF/jsp/page/elements/moduleTree.jsp, view/src/main/webapp/WEB-INF/jsp/tags/propertyRender.tld, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/FiboModule.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlDetails.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/WeaselOntologyManager.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/FiboDataHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java
Integrate class/property/individual view with modularization. Displaying the module tree on the right. Add icon insted _(Show meta)_ .
=> Integrate elements view with modularization

view/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/TreeRenderTag.java, view/src/main/webapp/WEB-INF/jsp/page/elements/viewGrouped.jsp, view/src/main/webapp/WEB-INF/jsp/search.jsp
> Swap columns; place modules on the left and the content viewer on the right.
=> Swap columns

CHANGELOG.md, config/pom.xml, config/src/main/java/org/edmcouncil/spec/fibo/config/utils/files/FileSystemManager.java, pom.xml, view/pom.xml, view/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/TreeRenderTag.java, view/src/main/webapp/WEB-INF/jsp/page/elements/header.jsp, view/src/main/webapp/WEB-INF/jsp/page/elements/viewGrouped.jsp, weasel/pom.xml, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlDetails.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/DataManager.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/AnnotationsDataHandler.java, weasel/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/FiboDataHandler.java
> - remove icon (doc with arrow)
> - add QName:XXX below a resource IRI
> - change name weasel_config.xml into fibo_viewer_config.xml
> - remove is defined by from Meta-info section; remove the section
=> Cosmetic changes

README.md, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/loader/ConfigLoader.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/loader/saxparser/WeaselConfigurationHandler.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/AppConfiguration.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/impl/ViewerCoreConfiguration.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlGroupedDetails.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphNode.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphRelation.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlGroupedDetailsProperties.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/DataManager.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/OntologyManager.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/AnnotationsDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/FiboDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/label/provider/LabelProvider.java, web-app/AboutFIBODev.ttl, web-app/src/main/java/org/edmcouncil/spec/fibo/view/service/SearchService.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/PropertyRenderTag.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/TaxonomyElementRenderTag.java, web-app/src/main/resources/static/css/main.css, web-app/src/main/webapp/WEB-INF/jsp/module.jsp, web-app/src/main/webapp/WEB-INF/jsp/page/elements/header.jsp, web-app/src/main/webapp/WEB-INF/jsp/page/elements/viewGrouped.jsp, web-app/src/main/webapp/WEB-INF/jsp/search.jsp
Temporary add imports in ontology file and repair request query with '#'
=> Temporary add imports in ontology file and repair request query with '#'

CHANGELOG.md, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/details/OwlDetails.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphNode.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphRelation.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/ViewerGraph.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/ViewerGraphJson.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/OntologyManager.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java, web-app/AboutFIBODev.ttl, web-app/src/main/webapp/WEB-INF/jsp/search.jsp
Change graph returning value in json
=> Change graph returning value in json

.github/pull_request_template.md, .gitignore
Created .github directory and created pull request template.
=> Create pull request template

api-doc/value.md, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/Pair.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/PairImpl.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/impl/element/RenameItem.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlDirectedSubClassesProperty.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlFiboModuleProperty.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/taxonomy/OwlStringPair.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/taxonomy/OwlTaxonomyElementImpl.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/taxonomy/OwlTaxonomyImpl.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/fibo/FiboDataHandler.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/PropertyRenderTag.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/util/custom/jsp/tag/TaxonomyElementRenderTag.java
Changing the taxonomy storing and returning a value: 
from value A, value B to IRI, and label.
=> change taxonomy storing and returnig value

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/RestrictionGraphDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java
Restrictions look like: 
> (controls some legal entity) or (has degree of control only degree of control) or (has nature of control only de facto control) 
were not displayed on the graph. Now works correctly.
=> Repair not displayed restrictions bug - merge to develop branch

CHANGELOG.md, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/RestrictionGraphDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java
Restrictions look like: 
> (controls some legal entity) or (has degree of control only degree of control) or (has nature of control only de facto control) 
were not displayed on the graph. Now works correctly.
=> Not displayed restrictions bug - merge to beta_v0.2.0 branch

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphElement.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphNode.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/GraphRelation.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/viewer/converter/vis/VisRelationConverter.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/vis/VisColor.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/graph/vis/VisRelation.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlGroupedDetailsProperties.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/RestrictionGraphDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/fibo/FiboDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/loader/DirectoryOntologyLoader.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/loader/FileOntologyLoader.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/text/TextDbItem.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/text/TextSearcherDb.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java, web-app/fibo_viewer_config.xml, web-app/ontologies/AboutFIBODev.rdf, web-app/ontologies/MetadataFIBO.rdf, web-app/src/main/resources/static/js/hint.js, web-app/src/main/webapp/WEB-INF/jsp/page/elements/detailsContent.jsp
Adding a new element (equivalent classes) to displaying on the graph.
=> Displaying equivalent classes on a graph

CHANGELOG.md, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java, web-app/config/ontology_config.xml
Signed-off-by: patrycjamia <patrycjamiazek17@gmail.com>
Incorrect graph display has been fixed. The restrictions with "or" are correctly displayed in the graph.
=> Fixed incorrect graph display (restriction with "or").

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/handler/fibo/FiboDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/scope/ScopeIriOntology.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/updater/UpdaterThread.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java, web-app/config/ontology_config.xml, web-app/src/main/resources/static/css/main.css, web-app/src/main/webapp/WEB-INF/jsp/page/elements/header.jsp, web-app/src/main/webapp/WEB-INF/jsp/page/elements/js/hint.jsp, web-app/src/main/webapp/WEB-INF/jsp/page/elements/viewGrouped.jsp
Fix ontology visitor to display shorter 'and' relation
=> Fix ontology visitor

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlAxiomPropertyEntity.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/scope/ScopeIriOntology.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/utils/OwlUtils.java, web-app/config/ontology_config.xml, web-app/fiboMapper/catalog-v001.xml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Fix the problem of not displaying ontology resources

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/RestrictionGraphDataHandler.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/ExpressionReturnedClass.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/visitor/OntologyVisitors.java, web-app/src/main/webapp/WEB-INF/jsp/page/elements/js/hint.jsp
Removal of the emerging additional node.
Possibility to make spaces in the search by one character.
Fixed bug with 'and' restrictions.
=> Fixed bugs in graph visitors

CHANGELOG.md, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/text/TextSearcherDb.java, web-app/config/search_config.xml
Search by using class names and definitions in hints and search bar.
=> Search by using class names and definitions

.gitignore, pom.xml, viewer-core/pom.xml, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/details/OntologySearcher.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/model/DetailsResult.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/model/ListResult.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/model/SearcherResult.java, web-app/config_integration_tests/groups_config.xml, web-app/config_integration_tests/ignore_to_display.xml, web-app/config_integration_tests/label_config.xml, web-app/config_integration_tests/ontology_config.xml, web-app/config_integration_tests/search_config.xml, web-app/ontologies_integration_tests/LegalPersons.rdf, web-app/ontologies_integration_tests/MetadataBE.rdf, web-app/pom.xml, web-app/src/main/java/org/edmcouncil/spec/fibo/view/controller/HintController.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/controller/ModuleApiController.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/controller/SearchApiController.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/controller/StatusController.java, web-app/src/main/java/org/edmcouncil/spec/fibo/view/service/OntologySearcherService.java, web-app/src/test/java/org/edmcouncil/spec/fibo/view/controller/BaseControllerIT.java, web-app/src/test/java/org/edmcouncil/spec/fibo/view/controller/HintControllerIT.java, web-app/src/test/java/org/edmcouncil/spec/fibo/view/controller/HintControllerTest.java, web-app/src/test/java/org/edmcouncil/spec/fibo/view/controller/ModuleApiControllerIT.java, web-app/src/test/java/org/edmcouncil/spec/fibo/view/controller/SearchApiControllerIT.java, web-app/src/test/resources/application.properties
Adds skeleton for unit and integration tests and add some tests.
=> Fibo 212 add integration tests

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/comparator/ComparatorWithAlphabeticalOrder.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/model/property/OwlAxiomPropertyValue.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/data/OwlDataHandler.java
Sort restrinctions in alphabetical order.
=> Sort restrinctions in alphabetical order

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/generator/DescriptionGenerator.java, web-app/src/test/java/org/edmcouncil/spec/fibo/weasel/ontology/generator/DescriptionGeneratorTest.java
Signed-off-by: Rafał Trójczak <Rafal.Trojczak@makolab.com>
=> FIBO-197 Sort generated definitions

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/searcher/text/TextSearcherDb.java
=> Fix bug in Levenshtein distance

config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/AppConfiguration.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/configuration/model/impl/ViewerCoreConfiguration.java, config-loader/src/main/java/org/edmcouncil/spec/fibo/config/utils/files/FileSystemManager.java, viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/generator/DescriptionGenerator.java, web-app/src/test/java/org/edmcouncil/spec/fibo/weasel/ontology/generator/DescriptionGeneratorTest.java
Signed-off-by: Rafał Trójczak <Rafal.Trojczak@makolab.com>
=> Change the way how generated descriptions are displayed

viewer-core/src/main/java/org/edmcouncil/spec/fibo/weasel/ontology/generator/DescriptionGenerator.java
Signed-off-by: Rafał Trójczak <Rafal.Trojczak@makolab.com>
=> Don't display empty list of generated descriptions

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/label/vocabulary/DefaultAppLabels.java
change header for direct sub properties:
for example:
Change 'Direct subObjectProperty' > 'Direct sub-properties'
=> change header for direct sub properties

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/fibo/FiboDataHandler.java
Add datatypes in extract resources.
=> datatypes are not displayed

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/details/OwlDetails.java
Removal of unnecessary variable "type"
#100
=> 100 Search Api Controller type is always null

README.md
=> Update README.md with Docker instructions

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/generator/DescriptionGenerator.java
=> Description generator simplified

onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/Application.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/FileService.java, pom.xml, style/checkstyle_suppressions.xml, style/google_checkstyle.xml
=> Add checking code style for the project

api-doc/rest_api.md, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/updater/UpdateBlocker.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/actuator/CustomHealthIndicator.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/actuator/HealthDetailsField.java, onto-viewer-web-app/src/main/resources/application.properties
Modify the Actuator prefix and add a custom status during the first load of the ontology.
#103
=> 103 modify the actulator prefix and add a custom

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/graph/VisitObjectUnionOf.java
Fixed incorrect display of restriction with 'or' in graph.
#118
=> 118 Fix incorrect display of restriction with 'or' in graph

onto-viewer-web-app/src/main/webapp/WEB-INF/jsp/page/elements/head.jsp
=> 122 Fix display hint on dev page 

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/AnnotationsDataHandler.java
=> 124 Different rendering of language tags 

onto-viewer-toolkit/pom.xml, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyConsistencyChecker.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/io/TextWriter.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/Goal.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/OptionDefinition.java
=> Add consistency checks tool to OV Toolkit

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigKeys.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/CoreConfiguration.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/KeyValueMapConfigItem.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/CommandLineOntologyLoader.java, onto-viewer-toolkit/pom.xml, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/mapping/model/Catalog.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/mapping/model/OntologyCatalogParser.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/mapping/model/Uri.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/OptionDefinition.java
=> Add handling for ontology mapping files in OV Toolkit

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/searcher/model/ListResult.java
Change typo in json returned. The html pages need to be updated.
#143
=>  143 typo in json returned for a search request 

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/fibo/FiboOntologyHandler.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractor.java
Improving the speed of OV Toolkit
=> 149 improve ov toolkit speed

api-doc/rest_api.md
=> Update REST API documentation for /actuator/info

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/AnnotationsDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/label/LabelProvider.java, onto-viewer-web-app/staticOntologies/CountryRepresentation.rdf, onto-viewer-web-app/staticOntologies/ISO3166-1-CountryCodes.rdf, onto-viewer-web-app/staticOntologies/ISO3166-2-SubdivisionCodes-CA.rdf, onto-viewer-web-app/staticOntologies/ISO3166-2-SubdivisionCodes-GB.rdf, onto-viewer-web-app/staticOntologies/ISO3166-2-SubdivisionCodes-MX.rdf, onto-viewer-web-app/staticOntologies/ISO3166-2-SubdivisionCodes-US.rdf, onto-viewer-web-app/staticOntologies/ISO3166-2-SubdivisionCodes.rdf, onto-viewer-web-app/staticOntologies/ISO639-1-LanguageCodes.rdf, onto-viewer-web-app/staticOntologies/ISO639-2-LanguageCodes.rdf, onto-viewer-web-app/staticOntologies/LanguageRepresentation.rdf
It turned out that the 'ISO3166-1-CountryCodes' ontology in the static ontologies was out of date. I have updated the file. What to do with the rest of the files in the 'staticOntologies' folder? It would be necessary to update them manually as well.
#151
=> 151 Missing label for Haiti

onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcher.java
=> Fix problem with Lucene when updating app

onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcher.java
=> Fix error in find search API

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/MemoryBasedConfigurationService.java, onto-viewer-config-loader/src/test/resources/integration_tests/config/groups_config.xml, onto-viewer-web-app/config/groups_config.xml, onto-viewer-web-app/integration_tests/config/groups_config.xml
Added deprecated type to configuration.
#163
=> 163 Display of deprecated entities

api-doc/rest_api.md, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/listener/MissingImportListenerImpl.java, onto-viewer-web-app/config/ontology_config.xml, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/controller/MissingImportsController.java
=> Create endpoint for missing imports

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/AutoOntologyLoader.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/CommandLineOntologyLoader.java
=> 181 Fix problems with imports in OV Toolkit

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java
Added subject to hide: SubPropertyOf, Range:, InverseOf.
„Fixes: #175
=> 175 Display of ontological characteristics of data properties

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/AutoOntologyLoader.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/UpdaterThread.java
=> Fix problems with loading ontologies

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java
=> Fix axiom numering when key is generated

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/AutoOntologyLoader.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologyLoadingProblem.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologyMapping.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologySource.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/utils/PathUtils.java, onto-viewer-web-app/config/ontology_config.xml
=> 189 to build-dev

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/AutoOntologyLoader.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologyLoadingProblem.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologyMapping.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/OntologySource.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/utils/PathUtils.java, onto-viewer-web-app/config/ontology_config.xml
Fixes problems with loading ontologies.
=> 189 problem with resolving local ontologies fix

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/GroupType.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/MemoryBasedConfigurationService.java, onto-viewer-config-loader/src/test/resources/integration_tests/config/groups_config.xml, onto-viewer-config-loader/src/test/resources/integration_tests/config/label_config.xml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-web-app/config/groups_config.xml, onto-viewer-web-app/config/label_config.xml
to check:
https://www.omg.org/spec/Commons/Designators/
https://spec.edmcouncil.org/idmp/ontology/ISO/ISO21090-HarmonizedDatatypes/
https://www.omg.org/spec/Commons/AnnotationVocabulary/
https://purl.iso.org/datatypes
https://www.omg.org/spec/Commons/Collections/isPartOf
https://spec.edmcouncil.org/idmp/ontology/MVP/UnifiedCodeForUnitsOfMeasure/UnifiedCodeForUnitsOfMeasureCodeSystemFullName
Fixed: #203
=> 203 Added new fields to the configuration file

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/AutoOntologyLoader.java
=> Fix problem with following links. Fixes: #209

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/label/LabelProvider.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/searcher/text/TextSearcherDb.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/utils/StringUtils.java, onto-viewer-web-app/config/ontology_config.xml
Pattern was added to the config because static ontology contain # which makes the modules display.
Fixed: #207
=> 207 Labels are not generated for some IRIs

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-web-app/config/ontology_config.xml, onto-viewer-web-app/fiboMapper/README
=> 212 Wrong search for inverse properties

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/DataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/UpdaterThread.java
Signed-off-by: Michał Daniel <michal.daniel@makolab.com>
Resolve problem with not updates modules
Fixes: #221 
I runed o-v with local loaded ontologies from directory, all works: modules, search, entity.
Next i deleted all ontologies from directory and make update request to check is all resourcess is reloaded correctly, modules is not reloaded/recreated and present old data, when i deleted directory modules should be empty.
=> 221 Resolve problem with not updates modules

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationData.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java, onto-viewer-core/src/test/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandlerTest.java
In ontology_config add field: automatic_creation_of_modules: false
Fixed: #224
=> 224 Module automatic creation needs a trigger

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/ApplicationConfigurationService.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/YamlFileBasedConfigurationService.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/UpdaterThread.java, onto-viewer-web-app/src/main/resources/application.properties
=> Add updating configuration

onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/config/ApplicationConfiguration.java
=> Fix problem with OV Toolkit

onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcher.java
=> Fix inadequate search results

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java
Case AnnotationProperty is empty because the default value is thing.
#244
=> 244 removed topAnnotationProperty from the taxonomy

onto-viewer-core/pom.xml, onto-viewer-toolkit/README.md, onto-viewer-toolkit/pom.xml, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyImportsMerger.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/Goal.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/OptionDefinition.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyImportsMergerTest.java, onto-viewer-toolkit/src/test/resources/logback-test.xml
=> Add merging ontologies in OV Toolkit

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/GroupsPropertyKey.java, onto-viewer-core/pom.xml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/mapping/model/EntityData.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/AnnotationsDataHandler.java, onto-viewer-toolkit/pom.xml, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/config/ApplicationConfiguration.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractor.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractorTest.java, onto-viewer-toolkit/src/test/resources/application-test.properties, onto-viewer-toolkit/src/test/resources/ontologies/test1.rdf
=> Fix problems with OV's extracting data

onto-viewer-core/pom.xml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/onto/OntologyResources.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/DataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/factory/CustomDataFactory.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/stats/OntologyStatsManager.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractorTest.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/UpdaterThread.java, pom.xml
=> 253 change the way ontology resources are handled

onto-viewer-config-loader/pom.xml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/details/OwlListDetails.java, onto-viewer-web-app/src/test/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcherTest.java
=> Fix problem with unit tests on Windows

onto-viewer-web-app/src/test/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcherTest.java, onto-viewer-web-app/src/test/resources/ontology/search_example_ontology.rdf
=> Add unit tests for LuceneSearcher

onto-viewer-toolkit/README.md, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyImportsMerger.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/OptionDefinition.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyImportsMergerTest.java
=> Add handling of version IRI for OV Toolkit

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/zip/ViewerZipFilesOperations.java
=> 266 Create directory when not exist for download ontology feature

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/Pair.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/comparator/ComparatorWithAlphabeticalOrder.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/property/OwlDetailsProperties.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/IndividualDataHandler.java
=> 262 When lists are expanded they need to be re-sorted 

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationData.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/resources/default_application_config.yaml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/DataHandler.java
1. We should consider whether to add a search by qname.
2. Configurations should be updated.
Fixed: #270
=> 270 show and allow to copy prefixed name 

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationData.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/resources/default_ontology_config.yaml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/ModuleHandler.java
=> Added a field with iri of the module to the configuration

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/stats/OntologyStatsManager.java
Not needed update config file.
Fixed: #283
=> 283 The IRI need to be moved to configuration file

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/OntologyVisitors.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/graph/VisitDataHasValue.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/graph/VisitObjectHasValue.java
=> 285 owl:hasValue restriction bug

api-doc/GRAPH.md, api-doc/README.md, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/graph/OntologyGraph.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/graph/viewer/ViewerGraphFactory.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/OwlDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/RestrictionGraphDataHandler.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/controller/api/GraphController.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/GraphService.java
=> 287 Added an endpoint to the graph handling 

onto-viewer-config-loader/pom.xml, onto-viewer-core/pom.xml
=> 289 Remove onto-viewer code vulnerabilities

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/YamlFileBasedConfigurationService.java
=> Path to catalog-v001.xml as zip_url fragment

onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/search/LuceneSearcher.java
=> Fix problem with find result size page

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/mapping/model/Catalog.java
Signed-off-by: Michał Daniel <michal.daniel@makolab.com>
Fixes #302
=> Ignore elements that o-v does not recognise in catalog.xml

api-doc/ACTUATOR.md, api-doc/ENTITY.md, api-doc/FIND.md, api-doc/GRAPH.md, api-doc/LOGS.md, api-doc/MISSINGIMPORTS.md, api-doc/MODULES.md, api-doc/STATS.md, api-doc/UPDATE.md
=> 291 Examples in api-doc 

api-doc/INTEGRATION.md, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationData.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/YamlFileBasedConfigurationService.java, onto-viewer-config-loader/src/main/resources/default_integration_config.yaml, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/exception/IntegrationNotConfiguredException.java, onto-viewer-web-app/pom.xml, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/controller/ApplicationExceptionHandler.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/controller/OntologyUpdateApiController.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/controller/api/IntegrationController.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/IntegrationService.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/LogsService.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/OntologyUpdateService.java, pom.xml
=> Add integration with data.world

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/CommandLineOntologyLoader.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/loader/LoadedOntologyData.java, onto-viewer-toolkit/pom.xml, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/io/TextWriter.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/model/ConsistencyCheckResult.java
=> Consistency check validation fix

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/property/OwlAnnotationPropertyValue.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/property/OwlAnnotationPropertyValueWithSubAnnotations.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/property/OwlDetailsProperties.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/RestrictionGraphDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/graph/GraphObjGenerator.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/data/AnnotationsDataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/metadata/MetadataHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/visitor/ContainsVisitors.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/ExpressionReturnedClass.java
=> Display annotations of annotations

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/maturity/MaturityLevelFactory.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/module/ModuleHandler.java
Extract maturity level from entity.
Resolves: #329
=> Extract maturity level from entity

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/mapping/model/EntityData.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/details/OwlDetails.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/VersionIriHandler.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/classes/ClassHandler.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractorTest.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/Updater.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/boot/UpdaterThread.java
=> 331 New presentation of versionIRI 

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/VersionIriHandler.java
=> 337 Fix problem with versionIri

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationData.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/GroupsPropertyKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/PairWithList.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/utils/files/FileSystemService.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/details/OwlGroupedDetails.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/maturity/MaturityLevelFactory.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/module/ModuleHandler.java, onto-viewer-toolkit/README.md, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/OntoViewerToolkitCommandLine.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractor.java, onto-viewer-toolkit/src/main/java/org/edmcouncil/spec/ontoviewer/toolkit/options/OptionDefinition.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/handlers/OntologyTableDataExtractorTest.java, onto-viewer-toolkit/src/test/java/org/edmcouncil/spec/ontoviewer/toolkit/options/CommandLineOptionsHandlerTest.java, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/IntegrationService.java
Add handling for custom maturity levels and extract-data columns for the extract-data goal in OV Toolkit
=> 335 add options for ov toolkit

onto-viewer-config-loader/pom.xml, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/YamlFileBasedConfigurationService.java
=> Add better handling of downloading config files

api-doc/INTEGRATION.md, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/utils/files/FileSystemService.java, onto-viewer-config-loader/src/main/resources/default_integration_config.yaml, onto-viewer-web-app/src/main/java/org/edmcouncil/spec/ontoviewer/webapp/service/IntegrationService.java
=> Add handling for accesstoken file for Describe functionality

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/data/handler/MaturityLevelHandler.java
=> Fix problem with handling maturity level

onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/model/ConfigurationKey.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/AbstractYamlConfigurationService.java, onto-viewer-config-loader/src/main/java/org/edmcouncil/spec/ontoviewer/configloader/configuration/service/YamlFileBasedConfigurationService.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/details/OwlListDetails.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/model/property/OwlDetailsProperties.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/DetailsManager.java, onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/service/EntitiesCacheService.java
=> 320 add handling for legal puning

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/service/ChangerIriToLabelService.java
For subAnnotations label i s generated.
=> fix labels in subannotations

onto-viewer-core/src/main/java/org/edmcouncil/spec/ontoviewer/core/ontology/visitor/graph/VisitSomeValuesFrom.java
=> 358 Incorrect display of restrictions in the graph
